# Site settings
title: Android Almería
email: info@androidalmeria.org
description: Comunidad de Desarrolladores Android de Almería.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://androidalmeria.org"
twitter_username: androidalmeria
github_username:  androidalmeria

# Build settings
markdown: kramdown
